name: Three

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  format_fail:
    name: First Format Run
    if: github.event.action != 'labeled'
    uses: ./.github/workflows/one.yml
    with:
      name: Failing Workflow
      fail: 'true'

  format_rerun:
    name: Second Format Run
    if: github.event.action == 'labeled' && github.event.label.name == 'rerun-tests'
    uses: ./.github/workflows/one.yml
    with:
      name: Call Workflow
      fail: 'false'

  push_fixes:
    name: Push Fixes
    needs: format_fail
    if: failure() && github.event.action == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Commit files
        id: git
        run: |
          echo "hello world" > hello.txt
          git config --local user.email "selenium-ci@users.noreply.github.com"
          git config --local user.name "Selenium CI Bot"
          git commit -am "fix formatting errors"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SELENIUM_CI_TOKEN }}
          branch: ${{ github.head_ref }}
      - name: Add label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['rerun-tests']
            })


  always_run:
    name: Like Tests
    if: always() && (github.event.action != 'labeled' || github.event.label.name == 'rerun-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          if [[ github.event_name == 'issues' ]]; then
            exit 0
          else
            exit 1
          fi
