name: Three

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  call_workflow_fail:
    name: Call Workflow Fails
    if: if github.event.action != 'labeled'
    uses: ./.github/workflows/one.yml
    with:
      name: Failing Workflow
      fail: 'true'

  call_workflow_rerun:
    name: Call Workflow Passes
    if: github.event.action == 'labeled' && github.event.label.name == 'rerun-tests')
    uses: ./.github/workflows/one.yml
    with:
      name: Call Workflow
      fail: 'false'

  use_results:
    name: Use Results
    if: github.event.action != 'labeled' || github.event.label.name == 'rerun-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if issue
        run: |
          if [[ github.event.action == 'labeled' && github.event.label.name == 'rerun-tests') ]]; then
            exit 1
          else
            exit 0
          fi
