name: One

on:
  workflow_call:
    inputs:
      name:
        description: Name of workflow
        required: false
        type: string
      fail:
        description: Force to fail
        required: false
        type: string
        default: 'false'

jobs:
  called_job:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4
      - name: Check failure
        run: |
          if [[ "${{ inputs.fail }}" == 'true' ]]; then
            exit 1
          fi
